name: Sync Backend to Fullstack

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout backend repo
        uses: actions/checkout@v3

      - name: Clone fullstack repo
        env:
          GH_TOKEN: ${{ secrets.FULLSTACK_TOKEN }}
        run: |
          git config --global user.name "marsaldaffa"
          git config --global user.email "marsaldaffa1@gmail.com"

          # Clone fullstack repo into ./fullstack
          git clone https://x-access-token:${GH_TOKEN}@github.com/marsaldaffa/fullstack.git fullstack

          # Create a temp folder to hold backend code
          mkdir backend-copy
